version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mfa
      - POSTGRES_PASSWORD=mfa
      - POSTGRES_DB=mfa
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py bootstrap && python manage.py runserver 0.0.0.0:8300'
    volumes:
      - .:/code
    environment:
      - MFA_DATABASE_NAME=mfa
      - MFA_DATABASE_USER=mfa
      - MFA_DATABASE_PASSWORD=mfa
      - MFA_DATABASE_HOST=db
      - MFA_DATABASE_PORT=5432
      - OSS2FA_ADMIN_USERNAME=${OSS2FA_ADMIN_USERNAME}
      - OSS2FA_ADMIN_EMAIL=${OSS2FA_ADMIN_EMAIL}
      - OSS2FA_ADMIN_PASSWORD=${OSS2FA_ADMIN_PASSWORD}

    ports:
      - '8300:8300'
    depends_on:
      - db
    links:
      - db
